[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
cardinal_rewards_center = "rwcn6Ry17ChPXpJCN2hoK5kwpgFarQqzycXwVJ3om7U"

[programs.devnet]
cardinal_rewards_center = "rwcn6Ry17ChPXpJCN2hoK5kwpgFarQqzycXwVJ3om7U"

[programs.testnet]
cardinal_rewards_center = "rwcn6Ry17ChPXpJCN2hoK5kwpgFarQqzycXwVJ3om7U"

[programs.localnet]
cardinal_rewards_center = "rwcn6Ry17ChPXpJCN2hoK5kwpgFarQqzycXwVJ3om7U"
