[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
cardinal_rewards_center = "rwcg7ZBhxV8ViZvueh5kRuQXkTGD8TmcoPmEpDutCUJ"

[programs.devnet]
cardinal_rewards_center = "rwcg7ZBhxV8ViZvueh5kRuQXkTGD8TmcoPmEpDutCUJ"

[programs.testnet]
cardinal_rewards_center = "rwcg7ZBhxV8ViZvueh5kRuQXkTGD8TmcoPmEpDutCUJ"

[programs.localnet]
cardinal_rewards_center = "rwcg7ZBhxV8ViZvueh5kRuQXkTGD8TmcoPmEpDutCUJ"
