[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
cardinal_rewards_center = "crcBwD7wUjzwsy8tJsVCzZvBTHeq5GoboGg84YraRyd"

[programs.devnet]
cardinal_rewards_center = "crcBwD7wUjzwsy8tJsVCzZvBTHeq5GoboGg84YraRyd"

[programs.testnet]
cardinal_rewards_center = "crcBwD7wUjzwsy8tJsVCzZvBTHeq5GoboGg84YraRyd"

[programs.localnet]
cardinal_rewards_center = "crcBwD7wUjzwsy8tJsVCzZvBTHeq5GoboGg84YraRyd"
