[provider]
cluster = "localnet"
wallet = "./tests/test-keypairs/test-key.json"

[programs.mainnet]
solana_nft_programs_rewards_center = "crcBwD7wUjzwsy8tJsVCzZvBTHeq5GoboGg84YraRyd"

[programs.devnet]
solana_nft_programs_rewards_center = "crcBwD7wUjzwsy8tJsVCzZvBTHeq5GoboGg84YraRyd"

[programs.testnet]
solana_nft_programs_rewards_center = "crcBwD7wUjzwsy8tJsVCzZvBTHeq5GoboGg84YraRyd"

[programs.localnet]
solana_nft_programs_rewards_center = "crcBwD7wUjzwsy8tJsVCzZvBTHeq5GoboGg84YraRyd"
